DEBUG: true

SERVER: "10.232.34.254"

AUDIO:
  SAMPLE_RATE: 16000
  HIGHPASS_HZ: 120.0
  LOWPASS_HZ: 5000.0
  CHUNK_SECONDS: 4
  BUFFER_SECONDS: 2
  AUDIO_DEVICE: null

WHISPER:
  MODEL_NAME: "tiny.en"
  MODEL_DEVICE: "cpu"
  MAX_BUFFER_LENGTH: 10

WAKE_WORD:
  MODEL_PATH: "wake_word/Turtlebot-2.onnx"
  WAKE_WORD_THRESHOLD: 0.002
  WAKE_WORD_COOLDOWN: 2.0
  WAKE_WORD_BLOCK_SIZE: 1280

ROBOT:
  DEFAULT_DISTANCE: 69.69
  DEFAULT_TURN_DEG: 69.69
  MOVE_VELOCITY: 0.20
  TURN_VELOCITY: 2.0

LOGIC:
  PAUSE_ITTERATIONS: 2