DEBUG: true

SERVER: "10.67.156.254"

AUDIO:
  SAMPLE_RATE: 16000
  HIGHPASS_HZ: 120.0
  LOWPASS_HZ: 5000.0
  CHUNK_SECONDS: 2
  BUFFER_SECONDS: 4
  AUDIO_DEVICE: null

WHISPER:
  MODEL_NAME: "tiny"
  MODEL_DEVICE: "cpu"
  MAX_BUFFER_LENGTH: 10

ROBOT:
  DEFAULT_DISTANCE_CM: 100
  DEFAULT_TURN_DEG: 90

LOGIC:
  PAUSE_ITTERATIONS: 2